### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by maharshmellow** [CMPUT404W20/CMPUT404-project-socialdistribution#77]
We want a search results page for the search bar at the top. We could do a dropdown but that would require a lot of searching against our database so we can just use a separate page to keep it simple.

**Comment by ceciliaccwei** [comment]
@maharshmellow For each author in the search result, should we have different buttons based on their relationship with the current user, e.g. Following, Follow, Friends etc? Or should we just direct the user to the user's profile page and the user can see the relationship there? Lemme know what you think.

**Comment by maharshmellow** [comment]
Maybe we can just keep it simple for now and just show the names that link to their profile page. We can do another PR for seeing the current relationship but since it's not a requirement we can come back to that later?

**Comment by ceciliaccwei** [comment]
Sounds good!
